version: "1.0"  # optional since v1.27.0
services:
    php1:
        image: php-projet-docker-3iw3
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
            - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
            - DB_USER=${DB_USER}
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
        working_dir: /var/www/html
        
        volumes:
            - ./volumes/app1/:/var/www/html # Charger le code source
            - ./volumes/config/php/php.ini:/usr/local/etc/php/php.ini #php.ini
            - ./volumes/config/ssl/:/etc/ssl_cert #certificat ssl
        depends_on:
            - mariadb

    composer: 
        image: composer
        working_dir: /var/www/html
        volumes: 
            - ./volumes/app1/:/var/www/html
        command: composer install
    
    composer2: 
        image: composer
        working_dir: /var/www/html
        volumes: 
            - ./volumes/app2/:/var/www/html
        command: composer install

    app1:
        image: nginx:latest
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
            - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
        
        volumes:
            - ./volumes/config/nginx/default.conf:/etc/nginx/conf.d/default.conf # Configuration NGINX
            - ./volumes/config/ssl/:/etc/ssl_cert #certificat ssl
            - ./volumes/log/nginx/:/var/log/nginx/ #Log nginx
            - ./volumes/app2/:/var/www/html # Charger le code source
        ports:
          - "80:80"
        depends_on:
            - php1
    php2:
        image: php-projet-docker-3iw3
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
            - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
            - DB_USER=${DB_USER}
            - DB_NAME=${DB_NAME}
            - DB_HOST=${DB_HOST}
        working_dir: /var/www/html
        volumes:
            - ./volumes/app2/:/var/www/html # Charger le code source
            - ./volumes/config/php/php.ini:/usr/local/etc/php/php.ini #php.ini
            - ./volumes/config/ssl/:/etc/ssl_cert #certificat ssl

        depends_on:
            - mariadb
       
    app2:
        image: nginx:latest
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
            - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
        
        volumes:
            - ./volumes/config/nginx/default2.conf:/etc/nginx/conf.d/default.conf # Configuration NGINX
            - ./volumes/config/ssl/:/etc/ssl_cert #certificat ssl
            - ./volumes/log/nginx2/:/var/log/nginx/ #Log nginx
            - ./volumes/app2/:/var/www/html # Charger le code source
        ports:
          - "81:80"
        depends_on:
            - php2
 
    
    mariadb:
        image: mariadb:latest
        restart: unless-stopped
        environment:
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
            - MARIADB_ROOT_PASSWORD=${MYSQL_ROOT_PASS}
        volumes:
            - ./volumes/database/:/var/lib/mysql # Liste toute nos base de donnée
            - ./volumes/config/sql/mariadb.cnf:/etc/mysql/mariadb.cnf # mariadb.cnf
            - ./volumes/config/sql/50-server.cnf:/etc/mysql/mariadb.conf.d/50-server.cnf # 50-server.cnf
            - ./volumes/config/ssl/:/etc/ssl_cert #certificat ssl


        ports:
          - "3306:3306"



    # phpMyAdmin Service
    phpmyadmin:
        image: phpmyadminssl
        volumes:
            - ./volumes/config/ssl/:/etc/ssl_cert #certificat ssl
            - ./volumes/config/phpmyadmin/000default.conf:/etc/apache2/sites-available/000-default.conf #conf apache phpmyadmin
            - ./volumes/config/php/php.ini:/usr/local/etc/php/php.ini #php.ini
        ports:
            - 8080:80
            - 8443:443
        environment:
            PMA_HOST: mariadb
            UPLOAD_LIMIT: 2048M
        depends_on:
            - mariadb

